apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: streaming-platform

spec:
  replicas: 1

  selector:
    matchLabels:
      app: minio

  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio

          args:
            - server
            - /data
            - --console-address
            - ":9001"

          ports:
            - containerPort: 9000
            - containerPort: 9001

          env:
            - name: MINIO_ROOT_USER
              value: admin

            - name: MINIO_ROOT_PASSWORD
              value: password123

          volumeMounts:
            - name: minio-storage
              mountPath: /data
      volumes:
        - name: minio-storage
          emptyDir: {}