apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: streaming-platform
spec:
  replicas: 1

  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: distributed-streaming-platform/discovery-server:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8761